teamName = [
    'The Skeptics','Skyhook Gravity','Bromania','Fisheye','Charismatic Sharpshooters','Tornadoes',
    'The Rhythms','Hashtags','Fly Fellas','Number Crunchers.','Slime Demons','Bloodbath Poets','Greasy Dishes',
    'Masters of Mayhem.','Team Synergy','Mute Assassins','The Rhythms','Courageous','Sinister Breed','The Waiver Wire',
    'Vendetta','Bone Crush Vigor','Crunch Puppets','Brew Masters','Fallen Angels','Sabotage','Diligent Kill Squad',
    'Those Guys','Kevlars','Kamikaze Masters','That Better Team','Havoc','Melodic Execution','Shadow Thugs',
    'Close Shave','Kamikaze Masters','Karma Synergy','Unbiased Executioners','The MudkipZ','The Mob','Loon Messiahs',
    'Justice of the Joyful','Angry Apes','Recreational Hazard','The Lint LickerZ','Junk In The Trunk','Smush Vikings',
    'Those Guys','Rockstar Lifestyle.','Skill Volt Theory','Lightning','Fly Fellas','Endurable Kill Thing',
    'Geeks and Freaks','Chick Magnets','Diabolic Destroyers','Stacks','Kamikaze Serenade','Bashful Blend',
    'Handymen','Sinister Breed','Skinner','Wild Stallions','Vicious Noobs','Tropical Storm','Handlebars','Rebellion',
    'Mauve Death','Vicious Midgets','All Men’s Club','Ironclad','Bloodbath and Beyond','Veins','Notorious Dudes',
    'Mad Thrashers.','Broneliness','Warglaive','Cult Cuts','Endurable Kill Thing','The Fixers','Not Fast But Furious.',
    'Spiffy Rebels','Poltergeist Kill','Digital Divas','Mirage Death','Trooper','Hangover','Taskforce','Z Light Admirals',
    'Antagonist Dreak Kill','Land Sharks.','Gunslingers','The Might Thrill','Panic Wriggle','Pain of Exile','Catalysts',
    'Feigned Anatomy','Lords of Absurd','Flack','Man-archy','Riot Privilege','Lords of Absurd','Breast Friends',
    'The Pace Makers.','Workout Divas','Insurgent','Bromosapiens','Supreme Skull Krushers','Frag Squad',
    'Bone Crush Vigor','Proud Fathers','The Pace Makers.','We Talk A Lot.','Chunky Monkees.','The Mighty Midgets',
    'Twisted Blisters.','Kung Fu Pandas','The Rhythms','Panic Mash','Tornadoes','Zombie Warfare',"Four Kings",
    'Team Target','Titanium','Dopaminers','Invincibles.Bloodbath and Beyond','Reaper',
    'Pollos Hermanos','Panic Mash','Snickerdoodles','Rot Kill Squad','Trigger Head Kill','Bad Companym n',
    'The Skeptics.','Twisted Minds','The Game','Four Kings','The Baha Badboys.','Skill Volt Theory','Sinister Epic',
    'Wild Stallions','P&L Ponies.','Yager Bombers','Dynamic Assailants','Diamond Girls','Silent Assassins',
    'Cannon','My Bros','Last Place Champions.','Bullets','Geronimo','Lunatic Assassins','Your Pace or Mine?',
    'Those Guys','Cobra','The Crew','Demented','Ballistic Preachers''Mania','Mellow Bone Mash','The Credit Crush.',
    'Nuestra Familia','Red rats','bone Crush Vigor','The “B” Squad.','Stacks','Math Mavericks.','iRobots','Geronimo',
    'The Mongols','The Muffin Tops','Four Kings','Recreational Hazard.','Bromagination','Pivotal Trip','Kung Fu Pandas',
    'Death Brigade','Greasy Dishes','That Better Team.','Society of the Rotten','The Vixens','Melodic Execution',
    'Mad Thrashers.','Proud Fathers','Epic Breed','Celestial Butchers','Dearest Sisters','Reflective Coercion',
    'Divergent Madness','Dearest Sisters','Calm Outlaws','Karma Poets','Hustle & Flo','10 hearts, 1 beat','Ironic Q',
    'Slaughter Bot Domain','Evil Wiggle','Napoleons','Angry Apes','Elegant Death Squad','Unquenchable Overkill',

]

nameInGame = [
    'PR0_GGRAM3D','101WaysToMeetYourMaker','3D Waffle','Accidental Genius','Acid Gosling','Admiral Tot',
    'AgentHercules','Airport Hobo','Alley Frog','Alpha','AlphaReturns','Angel','AngelsCreed',
    'Arsenic Coo','Atomic Blastoid','Automatic Slicer','Baby Brown','Back Bett','Bad Bunny',
    'Bazooka Har-de-har','Bearded Angler','Beetle King','Betty Cricket','Bit Sentinel','Bitmap',
    'BlacKitten','Blister','Blistered Outlaw','Blitz','BloodEater','Bonzai','BoomBeachLuvr',
    'BoomBlaster','Bootleg Taximan','Bowie','Bowler','Breadmaker','Broomspun','Buckshot',
    'Bug Blitz','Bug Fire','Bugger','Cabbie','Candy Butcher','Capital F','Captain Peroxide',
    'Celtic Charger','Centurion Sherman','Cereal Killer','Chasm Face','Chew Chew','Chicago Blackout',
    'Chip Queen','ChocoNutsX','Chocolate Thunder','Chuckles','Club Nola','CoB@lt','CobraBite','Cocktail',
    'CollaterolDamage','CommandX','Commando','Congo Wire','Cool Iris','Cool Whip','Cosmo','Crash Override',
    'Crash Test','Crazy Eights','Criss Cross','Cross Thread','Cujo','Cupid Dust','Daffy Girl','Dahlia Bumble',
    'DaisyCraft','Dancing Madman','Dangle','DanimalDaze','Dark Horse','Darkside Orbit','Darling Peacock',
    'Day Hawk','Desert Haze','Desperado','Devil Blade','Devil Chick','Dexter','Diamond Gamer','Digger',
    'Disco Potato','Disco Thunder','DiscoMate','Don Stab','Doz Killer','Dredd','DriftDetector',
    'DriftManiac','Drop Stone','Dropkick','Drugstore Cowboy','DuckDuck','Earl of Arms','Easy Sweep',
    'Eerie Mizzen','ElactixNova','Elder Pogue','Electric Player','Electric Saturn','Ember Rope','Esquire',
    'ExoticAlpha','EyeShooter','Fabulous','Fast Draw','FastLane','Father Abbot','FenderBoyXXX',
    'Fennel Dove','Feral Mayhem','Fiend Oblivion','FifthHarmony','Fire Feline','Fire Fish','FireByMisFire',
    'Fist Wizard','Flakes','Flame OUT','Flint','FlyGuardX','Flying Doodle','FrankenGrin','Freak','Frozen Explosion',
    'Gadget','Gas Man','General Broomdog','General Finish','Ghostrider','Global meltdown','Glyph',
    'Goatee Shield','Gov Skull','Grave Digger','Greek Rifle','Green Ghost','Green Scavenger','Guillotine',
    'Gullyway','Guncap Slingbad','Gunhawk','HeroOfBlackday','High Kingdom Warrior','Highlander Monk','Hightower',
    'Hog Butcher','HollySparta','Houston','Houston Rocket','Hyper','Hyper Kong','Impulsive Flower',
    'Indiana','IonicHound','Jack Cassidy','Jelly Camber','Jester','JesterZilla','JigKraken','Jigsaw',
    'Jokers Grin','Judge','Junkyard Dog','K-9','K-Tin Man','Keystone','KiTParty','Kickstart','Kill Switch',
    'Killah Goose','Kingfisher','KingofWolfstreet','Kitchen','Knight Light','Knuckles','Koi Diva',
    'LFAKing','Lady Killer','Landfill Max','Lava Nibbler','Lazy Killer',
    'LeSpank','LexusGTXXX','LifeRobber','Light Lion','LightInOut','Liquid Death','Liquid Science','Little Cobra'
]

userData = [
    'KathleenCross@kompetez',  'AlbertBauer@kompetez',  'MollyDuran@kompetez', 'SamanthaThomas@kompetez',
    'KimberlyBrown@kompetez',  'CoreyWashington@kompetez',  'PatriciaCruz@kompetez',  'DeniseMeyers@kompetez',  'DawnVargas@kompetez',
    'ChristineRobbins@kompetez',  'JamieThomas@kompetez',  'StacyBrown@kompetez',  'JasminLopez@kompetez',
    'RachelDominguez@kompetez',  'WillieAnderson@kompetez',  'NathanielJohnson@kompetez',  'ElizabethDiaz@kompetez',  'VincentHansen@kompetez',
    'EricHarrington@kompetez',  'SusanGross@kompetez',  'HenryPhillips@kompetez',  'TerriRivera@kompetez',  'AlanBuckley@kompetez',
    'GregoryHoffman@kompetez',  'JenniferPruitt@kompetez',  'TimothyGallagher@kompetez',  'CrystalPeterson@kompetez',  'RosePerry@kompetez',
    'HannahBanks@kompetez',  'Mr.JacobWilson@kompetez',  'DavidMitchell@kompetez',  'TeresaNelson@kompetez',  'MitchellRivera@kompetez',
    'JacobLittle@kompetez',  'BreannaLe@kompetez',  'RussellReyes@kompetez',
    'MariaWilliams@kompetez',  'JacobBurgess@kompetez',  'AbigailBrown@kompetez',  'ChadEspinoza@kompetez',  'ChristopherNichols@kompetez',
    'ChristopherDavis@kompetez',  'SamanthaMayerMD@kompetez',  'ElizabethGonzalez@kompetez',  'AprilHoover@kompetez',  'MatthewLopez@kompetez',
    'BeckyJacobson@kompetez',  'LauraSmith@kompetez',  'SamuelDavis@kompetez',  'MichealGriffin@kompetez',  'IsabellaJarvis@kompetez',  'AlexisBennett@kompetez',
    'ShellyChavez@kompetez',  'EarlThomas@kompetez',  'KylieFitzgerald@kompetez',  'TammyNoble@kompetez',  'VeronicaCherry@kompetez',  'DennisHoffman@kompetez',
    'AlexaWoods@kompetez',  'JeffreyMaxwell@kompetez',  'SydneyWest@kompetez',  'KeithWashington@kompetez',  'RichardAcosta@kompetez',  'DeborahDunnMD@kompetez',
    'DorothyFuller@kompetez',  'SarahPeters@kompetez',  'NathanSimmons@kompetez',  'LouisRodriguez@kompetez',  'JamesTaylor@kompetez',  'DarrellCain@kompetez',
    'MarkMorris@kompetez',  'OscarHopkins@kompetez',  'DebraJones@kompetez',  'TimothyEvans@kompetez',  'JillCampbell@kompetez',  'ErinMiller@kompetez',
    'DylanGardner@kompetez',  'MeganCrosby@kompetez',  'AlisonHill@kompetez',  'MarkMartin@kompetez',  'ChristinaBell@kompetez',  'VictoriaWhite@kompetez',
    'TracyValencia@kompetez',  'JohnMccarthy@kompetez',
    'FaithSellers@kompetez',  'DebraSmith@kompetez',  'HunterCooper@kompetez',  'HeatherStone@kompetez',  'PhilipBlackwell@kompetez',
    'RobertChavez@kompetez',  'Mr.DwayneWalker@kompetez',  'BrianCurtis@kompetez', 'KimberlyMcgee@kompetez',  'RonaldWebb@kompetez',
    'MelissaGarcia@kompetez',  'ScottClark@kompetez',  'JenniferEvans@kompetez',  'MicheleSmith@kompetez',  'RonaldThomas@kompetez',
    'JerryMorrow@kompetez',  'MatthewDiaz@kompetez',  'RebeccaGutierrez@kompetez',  
    'EdwardReid@kompetez',  'CameronWatkins@kompetez',
    'CathyEvans@kompetez',  'JoshuaSullivan@kompetez',  'VickiHuff@kompetez',  'MichaelHerrera@kompetez',  'MatthewRyan@kompetez',
    'MargaretJohnston@kompetez',  'AngelSmith@kompetez',  'TeresaHarris@kompetez',  'SoniaLambert@kompetez',  'CaseyJones@kompetez',
    'TinaRasmussen@kompetez',  'DavidGonzales@kompetez',  'CarrieOneal@kompetez',  'EricTurner@kompetez',  'LindseyMiller@kompetez',
    'DonaldJohnson@kompetez',  'CharlesFryII@kompetez',  'TaylorRivera@kompetez',  'JeffreyDalton@kompetez',  'AnnaGarza@kompetez',
    'ElizabethBowman@kompetez',  'JosephMacias@kompetez',  'JasonRowe@kompetez',  'LauraAnderson@kompetez',  'HaileyBarker@kompetez',
    'JoelCannon@kompetez',  'DanielleDuran@kompetez',  'KatherineBeck@kompetez',  'AlanThompson@kompetez',  'SamuelMartin@kompetez',
    'RickHartman@kompetez',  'RobertCurry@kompetez',  'JenniferPeterson@kompetez',  'JohnCantrell@kompetez',  'Mr.DannyRobertson@kompetez',
    'RobertPatrick@kompetez', 'ThomasNorton@kompetez',  'JudyJohnson@kompetez',  'DennisVasquez@kompetez',  'OscarBradley@kompetez',
    'AlyssaMartinez@kompetez', 'MichaelFlores@kompetez', 'EmilyBrown@kompetez',  'TylerPayne@kompetez',  'AngelaBrown@kompetez',
    'GinaReid@kompetez',  'KarinaGross@kompetez', 'MichelleCarlson@kompetez',  'CandiceGardner@kompetez',  'BrittanyYang@kompetez',
    'GabrielBowers@kompetez',  'JamesHawkins@kompetez',  'ChelseaBryant@kompetez',  'BrianGarcia@kompetez',  'JenniferRichPhD@kompetez',
    'StaceyEllis@kompetez',  'MaryMcintosh@kompetez',  'LeroyPetersen@kompetez',  'WilliamThompson@kompetez',  'AndreaSnyder@kompetez',
    'KristopherHamilton@kompetez',  'MatthewJohnson@kompetez',  'MackenzieFleming@kompetez',  'DerrickPerry@kompetez',  'MichaelMiller@kompetez',
    'DavidRuiz@kompetez',  'JudyRivera@kompetez',  'DouglasWilliams@kompetez',  'DestinySmith@kompetez',  'ShelbyOlson@kompetez',  'JeanJones@kompetez',
    'NicoleSingh@kompetez',  'KatieStephens@kompetez',  'KendraBecker@kompetez',  'ScottMorgan@kompetez',  'PaulaPrice@kompetez',
    'ChristopherWelch@kompetez',  'RobinLawrence@kompetez',  'DavidBrown@kompetez',  'JohnFrey@kompetez',  'LesliePrice@kompetez',
    'AmandaAdkins@kompetez',  'MichaelBaker@kompetez',  'KevinLin@kompetez',  'RobynBrown@kompetez',  'AlbertJones@kompetez',
    'MarioBrewer@kompetez',  'TonyaHanson@kompetez',  'FeliciaKoch@kompetez',  'JosephZimmerman@kompetez',  'ChadClark@kompetez',
    'TeresaButler@kompetez',  'DennisRamirez@kompetez',  'JasmineMiller@kompetez'
]
